import Head from "next/head";
import Headder from "@/components/Headder";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={`   `}>
        <Headder />
        <Footer />
      </div>
    </>
  );
}
