import Head from "next/head";

import { ModeToggle } from "@/components/theme/ModeToggle";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={`   `}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <ModeToggle />
      </div>
    </>
  );
}
